version: 2
jobs:
  build:
    docker:
      - image: rocker/verse:latest

    steps:
      - checkout

      - run: 
          name: Fix Rcpp build settings
          command: |
            mkdir ~/.R
            cp ./makevars ~/.R/Makevars
          
      - run:
          name: Runs tests / checks
          command: Rscript -e "devtools::check()"
          
      - run:
          name: Code Coverage
          command: Rscript -e "covr::codecov()"
